language: ruby
rvm:
- 2.2

install: gem install jekyll html-proofer jekyll-sitemap
script: scripts/build.sh

# branch whitelist
branches:
  only:
  - master
  - gh-pages     # test the gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  # on:
  #   branch: gh-pages


  #   after_success: |
  # if [ -n "$GITHUB_API_KEY" ]; then
  #   cd "$TRAVIS_BUILD_DIR"
  #   # This generates a `web` directory containing the website.
  #   make web
  #   cd web
  #   git init
  #   git checkout -b gh-pages
  #   git add .
  #   git -c user.name='travis' -c user.email='travis' commit -m init
  #   # Make sure to make the output quiet, or else the API token will leak!
  #   # This works because the API key can replace your password.
  #   git push -f -q https://<me>:$GITHUB_API_KEY@github.com/<me>/<myrepo>-gh-pages gh-pages &2>/dev/null
  #   cd "$TRAVIS_BUILD_DIR"
  # fi